### ISSUE TITLE
Opening images as links decensors them

### ISSUE THREAD

**Issue by keanureeves298** [rob204/Web-Cleaner-Chrome-Extension#4]
Opening an image on Sankaku complex by left clicking it, opening "image" in a new tap, or copying the image address opens the image censored. However, when right click, and hit "open link in a new tab" the image opens uncensored, even though the scanner detects it and says its blocking it. It blurs the image initially, so it seems to detect it, but not censor it.

https://chan.sankakucomplex.com/post/show/6312263 (SFW)

right click "open link in a new tab" decensors it
anything else, keeps it.
likewise, copying the link address and opening it that way makes it uncensored as well, so its something with opening images as links rather than images.

**Comment by rob204** [comment]
Thank you for mentioning this behavior.

As far as I can see we actually censor the image. You say that image is *not* censored. At first it looks like a graphics glitch. When you rescale the the browser window, the image collapses to 0x0 pixels. In the developers console you can actually see that we replaced the image src. But now even when we manually resize the image element, it still displays the original untampered image data.

At first appearance image documents look very similar to regular html documents. That's why I supposed we could just adopt the same procedure. But now it seems they contain way too much C++ magic.

Two observations regarding image documents:
1. The image element magically displays the original image data, no matter what you set as src.
2. The image element magically changes its width and height attributes so it always perfectly fits into the viewport. Except when you mess with the src, then it collapses to 0x0 pixels. Also there's a separate view mode with 100% zoom, but that doesn't work either.

So I see two alternatives:
1. We replace the original image element and imitate the resizing functionality with JavaScript.
2. We let chromium somehow create a new image document from the censored image.

Alternative 2 seems to be very difficult or impossible. So I will try to implement alternative 1.
